# Generated by Django 5.0.2 on 2024-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_pdf_room_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
